server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wucong-github/cloud2020-config.git
       # 搜索目录
          search-paths:
            -cloud2020-config
      # 读取分支
      label: master

#rabbitmq 相关配置
  rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'




eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
